name: Criar pasta e arquivo HTML no Github Pages

on:
  workflow_dispatch:
    inputs:
      platform_name:
        description: 'Nome da plataforma'
        required: true
        type: string
env:
  PLATFORM_EMOJI:

permissions:
    id-token: write
    pages: write
    contents: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Definir nome da plataforma
        id: set_platform_name
        run: |
          echo "Nome da plataforma: ${{ inputs.platform_name }}"
          echo "::set-output name=platform_name::${{ inputs.platform_name }}"

      - name: Criar pasta
        run: |
          mkdir -p "public"

      - name: Define platform emoji
        run: |
          if [ "${{ inputs.platform_name }}" == "ios" ]; then
            export PLATFORM_EMOJI=🍎
          elif [ "${{ inputs.platform_name }}" == "android" ]; then
            export PLATFORM_EMOJI=🤖
          fi

      - name: print
        run: |
          echo ${{ env.PLATFORM_EMOJI }}

      - name: Criar arquivo index.html
        run: |
          echo "<html><body><h1>${{ inputs.platform_name }} - ${{ env.PLATFORM_EMOJI }}</h1></body></html>" > "public/index.html"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: reports
          target-folder: ${{ inputs.platform_name }}

