name: Criar pasta e arquivo HTML no Github Pages

on:
  workflow_dispatch:
    inputs:
      platform_name:
        description: 'Nome da plataforma'
        required: true
        type: string

permissions:
    id-token: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Definir nome da plataforma
        id: set_platform_name
        run: |
          echo "Nome da plataforma: ${{ inputs.platform_name }}"
          echo "::set-output name=platform_name::${{ inputs.platform_name }}"

      - name: Criar pasta
        run: |
          mkdir -p "public/${{ inputs.platform_name }}"

      - name: Criar arquivo index.html
        run: |
          echo "<html><body><h1>${{ inputs.platform_name }}</h1></body></html>" > "public/${{ inputs.platform_name }}/index.html"

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4

