name: Criar pasta e arquivo HTML no Github Pages

on:
  workflow_dispatch:
    inputs:
      platform_name:
        description: 'Nome da plataforma'
        required: true
        type: string

permissions:
    id-token: write
    pages: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Definir nome da plataforma
        id: set_platform_name
        run: |
          echo "Nome da plataforma: ${{ inputs.platform_name }}"
          echo "::set-output name=platform_name::${{ inputs.platform_name }}"

      - name: Criar pasta
        run: |
          mkdir -p "public"

      - name: Criar arquivo index.html
        run: |
          echo "<html><body><h1>${{ inputs.platform_name }}</h1></body></html>" > "public/index.html"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: main
          target-folder: ${{ inputs.platform_name }}

