on:
    workflow_call:
      inputs:
        result:
            description: 'test result'
            required: true
            type: string
        platform:
            description: 'platform'
            required: true
            type: string
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
        - name: Print
          run: echo ${{ inputs.result }}
        
        - name: Print lower
          run: |
            echo "${inputs.platform,,}"

        - name: Send Success
          if: ${{ inputs.result == 'success' }}
          run: |
            echo sucesso

        - name: Send Error
          if: ${{ inputs.result == 'failure' }}
          run: |
            echo sucesso    